# =====================================================
#
#      Makefile
#      Uinxed-Kernel compile script
#
#      2024/6/23 By Rainy101112
#      Based on Apache 2.0 open source license.
#      Copyright © 2020 ViudiraTech, based on the Apache 2.0 license.
#
# =====================================================

ifeq ($(VERBOSE), 1)
  Q=
else
  Q=@
endif

C_SOURCES  := $(shell find * -name "*.c")
C_HEADERS  := $(shell find * -name "*.h")
OBJS       := $(C_SOURCES:%.c=%.o)
DEPS       := $(OBJS:%.o=%.d)
LIBS       := $(wildcard libs/lib*.a)
PWD        := $(shell pwd)

CC_FLAGS   := -Wall -Wextra -O3 -g3 -m64 -fpie -ffreestanding -fno-optimize-sibling-calls -fno-stack-protector -fno-omit-frame-pointer -mstackrealign -mno-red-zone -I include -MMD
LD_FLAGS   := -nostdlib -pie -T assets/linker.ld -m elf_x86_64

QEMU       := qemu-system-x86_64
QEMU_FLAGS := -machine q35 -bios assets/ovmf-code.fd

all: Uinxed-x64.iso

%.o: %.c
	$(Q)printf "  CC      $@\n"
	$(Q)$(CC) $(CC_FLAGS) -c -o $@ $<

%.fmt: %
	$(Q)printf "  FORMAT  $<\n"
	$(Q)clang-format -i $<

%.tidy: %
	$(Q)printf "  TIDY    $<\n"
	$(Q)clang-tidy $< -- $(CC_FLAGS)

info:
	$(Q)printf "Uinxed-Kernel Compile Script.\n"
	$(Q)printf "Copyright 2020 ViudiraTech, based on the Apache 2.0 license.\n"
	$(Q)printf "Based on Apache 2.0 open source license.\n\n"

UxImage: $(OBJS) $(LIBS)
	$(Q)printf "  LD      $@\n"
	$(Q)$(LD) $(LD_FLAGS) -o $@ $^

Uinxed-x64.iso: info UxImage
	$(Q)printf "  XORRISO $@\n\n"
	$(Q)cp -a assets/Limine iso
	$(Q)cp $(word 2,$^) iso/EFI/Boot
	$(Q)xorriso -as mkisofs -R -r -J -b Limine/limine-bios-cd.bin -no-emul-boot -boot-load-size 4 -boot-info-table \
                -hfsplus -apm-block-size 2048 -efi-boot-part --efi-boot-image --protective-msdos-label \
                --efi-boot Limine/limine-uefi-cd.bin -o $@ iso
	$(Q)$(RM) -rf iso
	$(Q)printf "Kernel: $(word 2,$^) is ready.\n"
	$(Q)printf "Image: $@ is ready.\n"
	$(Q)printf "Compilation complete.\n"

.PHONY: help run clean format check gen.clangd menuconfig

help: info
	$(Q)printf "Uinxed-Kernel Makefile Usage:\n"
	$(Q)printf "  make all         - Build the entire project.\n"
	$(Q)printf "  make run         - Run the Uinxed-x64.iso in QEMU.\n"
	$(Q)printf "  make clean       - Clean all generated files.\n"
	$(Q)printf "  make format      - Format all source files using clang-format.\n"
	$(Q)printf "  make check       - Run static code checks using clang-tidy.\n"
	$(Q)printf "  make gen.clangd  - Generate .clangd configuration file.\n"
	$(Q)printf "  make help        - Display this help message.\n"

run: info Uinxed-x64.iso
	$(QEMU) $(QEMU_FLAGS) -cdrom $(word 2,$^)

clean: info
	$(Q)$(RM) $(OBJS) $(DEPS) UxImage Uinxed-x64.iso
	$(Q)printf "Clean completed.\n"

format: info $(C_SOURCES:%=%.fmt) $(C_HEADERS:%=%.fmt)
	$(Q)printf "\nCode Format complete.\n"

check: info $(C_SOURCES:%=%.tidy) $(C_HEADERS:%=%.tidy)
	$(Q)printf "\nCode Checks complete.\n"

gen.clangd: info
	$(Q)$(RM) -f .clangd
	$(Q)echo "# Generated by Makefile" >> .clangd
	$(Q)sed "s/\$${workspaceFolder}/$(subst /,\/,${PWD})/g" .clangd_template >> .clangd
	$(Q)printf ".clangd configuration generated.\n"

-include $(DEPS)
