# =====================================================
#
#      kconfig.mk
#      Uinxed-Kernel kconfig script
#
#      2026/8/12 By MicroFish
#      Copyright (C) 2020 ViudiraTech, based on the Apache 2.0 license.
#
# =====================================================

ifneq ($(wildcard .config),)
  include .config
else ifneq ($(wildcard .config-default),)
  include .config-default
else
  $(warning No configuration file (.config or .config-default) found; build will continue with defaults)
endif

ifeq ($(CONFIG_KERNEL_LOG), y)
  C_CONFIG += -DCONFIG_KERNEL_LOG=1
else
  C_CONFIG += -DCONFIG_KERNEL_LOG=0
endif

ifneq ($(CONFIG_TTY_DEFAULT_DEV),)
  C_CONFIG += -DCONFIG_TTY_DEFAULT_DEV=\"$(CONFIG_TTY_DEFAULT_DEV)\"
endif

ifeq ($(CONFIG_VT), y)
  C_CONFIG += -DCONFIG_VT=1
else
  C_CONFIG += -DCONFIG_VT=0
endif

ifneq ($(CONFIG_VT_COUNT),)
  C_CONFIG += -DCONFIG_VT_COUNT=$(CONFIG_VT_COUNT)
endif

ifneq ($(CONFIG_TTY_BUF_SIZE),)
  C_CONFIG += -DCONFIG_TTY_BUF_SIZE=$(CONFIG_TTY_BUF_SIZE)
endif

ifneq ($(CONFIG_TTY_CORE_BUFFER_SIZE),)
  C_CONFIG += -DCONFIG_TTY_CORE_BUFFER_SIZE=$(CONFIG_TTY_CORE_BUFFER_SIZE)
endif

ifeq ($(CONFIG_UNIX98_PTYS), y)
  C_CONFIG += -DCONFIG_UNIX98_PTYS=1
else
  C_CONFIG += -DCONFIG_UNIX98_PTYS=0
endif

ifeq ($(CONFIG_UNIX98_PTY_MAX),)
  C_CONFIG += -DCONFIG_UNIX98_PTY_MAX=4096
else
  C_CONFIG += -DCONFIG_UNIX98_PTY_MAX=$(CONFIG_UNIX98_PTY_MAX)
endif

ifneq ($(CONFIG_SERIAL_BAUD_RATE),)
  C_CONFIG += -DCONFIG_SERIAL_BAUD_RATE=$(CONFIG_SERIAL_BAUD_RATE)
endif

ifneq ($(CONFIG_SERIAL_DATA_BITS),)
  C_CONFIG += -DCONFIG_SERIAL_DATA_BITS=$(CONFIG_SERIAL_DATA_BITS)
endif

ifneq ($(CONFIG_SERIAL_STOP_BITS),)
  C_CONFIG += -DCONFIG_SERIAL_STOP_BITS=$(CONFIG_SERIAL_STOP_BITS)
endif

ifneq ($(CONFIG_SERIAL_PARITY),)
  C_CONFIG += -DCONFIG_SERIAL_PARITY=$(CONFIG_SERIAL_PARITY)
endif

ifeq ($(CONFIG_SERIAL), y)
  C_CONFIG += -DCONFIG_SERIAL=1
else
  C_CONFIG += -DCONFIG_SERIAL=0
endif

ifneq ($(CONFIG_CPU_MAX_COUNT),)
  C_CONFIG += -DCONFIG_CPU_MAX_COUNT=$(CONFIG_CPU_MAX_COUNT)
endif

# Kernel code must not emit FPU/SSE/AVX instructions implicitly: any
# kernel floating-point use must opt in per-file (or per-function) with
# `#pragma GCC target("sse2")` and be wrapped in kernel_fpu_begin()/
# kernel_fpu_end() (see include/arch/fpu.h).
ifeq ($(CONFIG_CPU_FEATURE_FPU), y)
  C_CONFIG += -DCONFIG_CPU_FEATURE_FPU=1
else
  C_CONFIG += -DCONFIG_CPU_FEATURE_FPU=0
endif

ifeq ($(CONFIG_CPU_FEATURE_SSE), y)
  C_CONFIG += -DCONFIG_CPU_FEATURE_SSE=1
else
  C_CONFIG += -DCONFIG_CPU_FEATURE_SSE=0
endif

ifeq ($(CONFIG_CPU_FEATURE_AVX), y)
  C_CONFIG += -DCONFIG_CPU_FEATURE_AVX=1
else
  C_CONFIG += -DCONFIG_CPU_FEATURE_AVX=0
endif

ifeq ($(CONFIG_CPU_FEATURE_AVX512), y)
  C_CONFIG += -DCONFIG_CPU_FEATURE_AVX512=1
else
  C_CONFIG += -DCONFIG_CPU_FEATURE_AVX512=0
endif

ifneq ($(CONFIG_KERNEL_HEAP_MAX_MIB),)
  C_CONFIG += -DCONFIG_KERNEL_HEAP_MAX_MIB=$(CONFIG_KERNEL_HEAP_MAX_MIB)
endif

ifneq ($(CONFIG_TIMER_HZ),)
  C_CONFIG += -DCONFIG_TIMER_HZ=$(CONFIG_TIMER_HZ)
endif

ifneq ($(CONFIG_SCHED_BASE_SLICE),)
  C_CONFIG += -DCONFIG_SCHED_BASE_SLICE=$(CONFIG_SCHED_BASE_SLICE)
endif

ifneq ($(CONFIG_SCHED_LATENCY),)
  C_CONFIG += -DCONFIG_SCHED_LATENCY=$(CONFIG_SCHED_LATENCY)
endif

ifneq ($(CONFIG_SCHED_MIN_GRANULARITY),)
  C_CONFIG += -DCONFIG_SCHED_MIN_GRANULARITY=$(CONFIG_SCHED_MIN_GRANULARITY)
endif

ifneq ($(CONFIG_SCHED_WAKEUP_GRANULARITY),)
  C_CONFIG += -DCONFIG_SCHED_WAKEUP_GRANULARITY=$(CONFIG_SCHED_WAKEUP_GRANULARITY)
endif

ifneq ($(CONFIG_SCHED_LOAD_BALANCE_INTERVAL),)
  C_CONFIG += -DCONFIG_SCHED_LOAD_BALANCE_INTERVAL=$(CONFIG_SCHED_LOAD_BALANCE_INTERVAL)
endif

ifneq ($(CONFIG_SCHED_BALANCE_BATCH),)
  C_CONFIG += -DCONFIG_SCHED_BALANCE_BATCH=$(CONFIG_SCHED_BALANCE_BATCH)
endif

ifneq ($(CONFIG_SCHED_MIGRATION_COOLDOWN),)
  C_CONFIG += -DCONFIG_SCHED_MIGRATION_COOLDOWN=$(CONFIG_SCHED_MIGRATION_COOLDOWN)
endif

ifneq ($(CONFIG_PROCESS_MAX_FD),)
  C_CONFIG += -DCONFIG_PROCESS_MAX_FD=$(CONFIG_PROCESS_MAX_FD)
endif

ifneq ($(CONFIG_PROCESS_TABLE_SIZE),)
  C_CONFIG += -DCONFIG_PROCESS_TABLE_SIZE=$(CONFIG_PROCESS_TABLE_SIZE)
endif

ifneq ($(CONFIG_KERNEL_WORKER_MAX),)
  C_CONFIG += -DCONFIG_KERNEL_WORKER_MAX=$(CONFIG_KERNEL_WORKER_MAX)
endif

ifneq ($(CONFIG_PROCESS_KERNEL_STACK),)
  C_CONFIG += -DCONFIG_PROCESS_KERNEL_STACK=$(CONFIG_PROCESS_KERNEL_STACK)
endif

ifneq ($(CONFIG_PROCESS_STACK_SIZE),)
  C_CONFIG += -DCONFIG_PROCESS_STACK_SIZE=$(CONFIG_PROCESS_STACK_SIZE)
endif

ifeq ($(CONFIG_INIT_MODULE), y)
  C_CONFIG += -DCONFIG_INIT_MODULE=1
else
  C_CONFIG += -DCONFIG_INIT_MODULE=0
endif

ifneq ($(CONFIG_INIT_PATH),)
  C_CONFIG += -DCONFIG_INIT_PATH=\"$(CONFIG_INIT_PATH)\"
endif

ifneq ($(CONFIG_PIPE_BUF_SIZE),)
  C_CONFIG += -DCONFIG_PIPE_BUF_SIZE=$(CONFIG_PIPE_BUF_SIZE)
endif

ifneq ($(CONFIG_PIPE_ADAPTIVE_SPIN_ITERS),)
  C_CONFIG += -DCONFIG_PIPE_ADAPTIVE_SPIN_ITERS=$(CONFIG_PIPE_ADAPTIVE_SPIN_ITERS)
endif

ifneq ($(CONFIG_SOCK_BUF_SIZE),)
  C_CONFIG += -DCONFIG_SOCK_BUF_SIZE=$(CONFIG_SOCK_BUF_SIZE)
endif

ifneq ($(CONFIG_SOCK_ACCEPT_QUEUE_MAX),)
  C_CONFIG += -DCONFIG_SOCK_ACCEPT_QUEUE_MAX=$(CONFIG_SOCK_ACCEPT_QUEUE_MAX)
endif

ifneq ($(CONFIG_EPOLL_MAX_FDS),)
  C_CONFIG += -DCONFIG_EPOLL_MAX_FDS=$(CONFIG_EPOLL_MAX_FDS)
endif

ifneq ($(CONFIG_FUTEX_HASH_BITS),)
  C_CONFIG += -DCONFIG_FUTEX_HASH_BITS=$(CONFIG_FUTEX_HASH_BITS)
endif

ifneq ($(CONFIG_INOTIFY_MAX_QUEUED_EVENTS),)
  C_CONFIG += -DCONFIG_INOTIFY_MAX_QUEUED_EVENTS=$(CONFIG_INOTIFY_MAX_QUEUED_EVENTS)
endif

ifneq ($(CONFIG_INOTIFY_MAX_USER_INSTANCES),)
  C_CONFIG += -DCONFIG_INOTIFY_MAX_USER_INSTANCES=$(CONFIG_INOTIFY_MAX_USER_INSTANCES)
endif

ifneq ($(CONFIG_INOTIFY_MAX_USER_WATCHES),)
  C_CONFIG += -DCONFIG_INOTIFY_MAX_USER_WATCHES=$(CONFIG_INOTIFY_MAX_USER_WATCHES)
endif

ifeq ($(CONFIG_NETLINK), y)
  C_CONFIG += -DCONFIG_NETLINK=1
else
  C_CONFIG += -DCONFIG_NETLINK=0
endif

ifeq ($(CONFIG_SYSVIPC), y)
  C_CONFIG += -DCONFIG_SYSVIPC=1
else
  C_CONFIG += -DCONFIG_SYSVIPC=0
endif

ifeq ($(CONFIG_POSIX_MQ), y)
  C_CONFIG += -DCONFIG_POSIX_MQ=1
else
  C_CONFIG += -DCONFIG_POSIX_MQ=0
endif

ifeq ($(CONFIG_NET), y)
  C_CONFIG += -DCONFIG_NET=1
else
  C_CONFIG += -DCONFIG_NET=0
endif

ifeq ($(CONFIG_INET), y)
  C_CONFIG += -DCONFIG_INET=1
else
  C_CONFIG += -DCONFIG_INET=0
endif

ifeq ($(CONFIG_E1000), y)
  C_CONFIG += -DCONFIG_E1000=1
else
  C_CONFIG += -DCONFIG_E1000=0
endif

ifeq ($(CONFIG_RTL8169), y)
  C_CONFIG += -DCONFIG_RTL8169=1
else
  C_CONFIG += -DCONFIG_RTL8169=0
endif

ifeq ($(CONFIG_RTL8139), y)
  C_CONFIG += -DCONFIG_RTL8139=1
else
  C_CONFIG += -DCONFIG_RTL8139=0
endif

ifeq ($(CONFIG_PS2_KEYBOARD_MOUSE), y)
  C_CONFIG += -DCONFIG_PS2_KEYBOARD_MOUSE=1
else
  C_CONFIG += -DCONFIG_PS2_KEYBOARD_MOUSE=0
endif

ifeq ($(CONFIG_PARPORT), y)
  C_CONFIG += -DCONFIG_PARPORT=1
else
  C_CONFIG += -DCONFIG_PARPORT=0
endif

ifneq ($(CONFIG_PARPORT_MAX_PORTS),)
  C_CONFIG += -DCONFIG_PARPORT_MAX_PORTS=$(CONFIG_PARPORT_MAX_PORTS)
endif

ifeq ($(CONFIG_ATA), y)
  C_CONFIG += -DCONFIG_ATA=1
else
  C_CONFIG += -DCONFIG_ATA=0
endif

ifeq ($(CONFIG_NVME), y)
  C_CONFIG += -DCONFIG_NVME=1
else
  C_CONFIG += -DCONFIG_NVME=0
endif

ifneq ($(CONFIG_NVME_MAX_CONTROLLERS),)
  C_CONFIG += -DCONFIG_NVME_MAX_CONTROLLERS=$(CONFIG_NVME_MAX_CONTROLLERS)
endif

ifneq ($(CONFIG_NVME_MAX_NAMESPACES),)
  C_CONFIG += -DCONFIG_NVME_MAX_NAMESPACES=$(CONFIG_NVME_MAX_NAMESPACES)
endif

ifneq ($(CONFIG_BLOCKDEV_MAX_TYPES),)
  C_CONFIG += -DCONFIG_BLOCKDEV_MAX_TYPES=$(CONFIG_BLOCKDEV_MAX_TYPES)
endif

ifneq ($(CONFIG_PARTITION_MAX_COUNT),)
  C_CONFIG += -DCONFIG_PARTITION_MAX_COUNT=$(CONFIG_PARTITION_MAX_COUNT)
endif

ifeq ($(CONFIG_SWAP), y)
  C_CONFIG += -DCONFIG_SWAP=1
else
  C_CONFIG += -DCONFIG_SWAP=0
endif

ifeq ($(CONFIG_INPUT_EVDEV), y)
  C_CONFIG += -DCONFIG_INPUT_EVDEV=1
else
  C_CONFIG += -DCONFIG_INPUT_EVDEV=0
endif

ifneq ($(CONFIG_INPUT_EVDEV_BUFSIZE),)
  C_CONFIG += -DCONFIG_INPUT_EVDEV_BUFSIZE=$(CONFIG_INPUT_EVDEV_BUFSIZE)
endif

ifneq ($(CONFIG_EVDEV_MAX_DEVICES),)
  C_CONFIG += -DCONFIG_EVDEV_MAX_DEVICES=$(CONFIG_EVDEV_MAX_DEVICES)
endif

ifeq ($(CONFIG_USB), y)
  C_CONFIG += -DCONFIG_USB=1
else
  C_CONFIG += -DCONFIG_USB=0
endif

ifeq ($(CONFIG_USB_UHCI), y)
  C_CONFIG += -DCONFIG_USB_UHCI=1
else
  C_CONFIG += -DCONFIG_USB_UHCI=0
endif

ifeq ($(CONFIG_USB_OHCI), y)
  C_CONFIG += -DCONFIG_USB_OHCI=1
else
  C_CONFIG += -DCONFIG_USB_OHCI=0
endif

ifeq ($(CONFIG_USB_EHCI), y)
  C_CONFIG += -DCONFIG_USB_EHCI=1
else
  C_CONFIG += -DCONFIG_USB_EHCI=0
endif

ifeq ($(CONFIG_USB_XHCI), y)
  C_CONFIG += -DCONFIG_USB_XHCI=1
else
  C_CONFIG += -DCONFIG_USB_XHCI=0
endif

ifeq ($(CONFIG_USB_HID), y)
  C_CONFIG += -DCONFIG_USB_HID=1
else
  C_CONFIG += -DCONFIG_USB_HID=0
endif

ifeq ($(CONFIG_USB_HUB), y)
  C_CONFIG += -DCONFIG_USB_HUB=1
else
  C_CONFIG += -DCONFIG_USB_HUB=0
endif

ifneq ($(CONFIG_USB_HUB_MAX_HUBS),)
  C_CONFIG += -DCONFIG_USB_HUB_MAX_HUBS=$(CONFIG_USB_HUB_MAX_HUBS)
endif

ifeq ($(CONFIG_USB_STORAGE), y)
  C_CONFIG += -DCONFIG_USB_STORAGE=1
else
  C_CONFIG += -DCONFIG_USB_STORAGE=0
endif

ifneq ($(CONFIG_USB_MSC_MAX_DISKS),)
  C_CONFIG += -DCONFIG_USB_MSC_MAX_DISKS=$(CONFIG_USB_MSC_MAX_DISKS)
endif

ifeq ($(CONFIG_DRM), y)
  C_CONFIG += -DCONFIG_DRM=1
else
  C_CONFIG += -DCONFIG_DRM=0
endif

ifeq ($(CONFIG_BOOT_LOGO), y)
  C_CONFIG += -DCONFIG_BOOT_LOGO=1
else
  C_CONFIG += -DCONFIG_BOOT_LOGO=0
endif

ifeq ($(CONFIG_VIRTIO), y)
  C_CONFIG += -DCONFIG_VIRTIO=1
else
  C_CONFIG += -DCONFIG_VIRTIO=0
endif

ifeq ($(CONFIG_VIRTIO_PCI), y)
  C_CONFIG += -DCONFIG_VIRTIO_PCI=1
else
  C_CONFIG += -DCONFIG_VIRTIO_PCI=0
endif

ifeq ($(CONFIG_VIRTIO_GPU), y)
  C_CONFIG += -DCONFIG_VIRTIO_GPU=1
else
  C_CONFIG += -DCONFIG_VIRTIO_GPU=0
endif

ifeq ($(CONFIG_SIMPLEDRM), y)
  C_CONFIG += -DCONFIG_SIMPLEDRM=1
else
  C_CONFIG += -DCONFIG_SIMPLEDRM=0
endif

ifneq ($(CONFIG_DRM_MAX_DEVICES),)
  C_CONFIG += -DCONFIG_DRM_MAX_DEVICES=$(CONFIG_DRM_MAX_DEVICES)
endif

ifneq ($(CONFIG_GEM_MAX_NAMES),)
  C_CONFIG += -DCONFIG_GEM_MAX_NAMES=$(CONFIG_GEM_MAX_NAMES)
endif

ifneq ($(CONFIG_PRIME_FD_MAX),)
  C_CONFIG += -DCONFIG_PRIME_FD_MAX=$(CONFIG_PRIME_FD_MAX)
endif

ifneq ($(CONFIG_GPU_MAX_GPU_DRIVERS),)
  C_CONFIG += -DCONFIG_GPU_MAX_GPU_DRIVERS=$(CONFIG_GPU_MAX_GPU_DRIVERS)
endif

ifneq ($(CONFIG_DRM_DEFAULT_WIDTH),)
  C_CONFIG += -DCONFIG_DRM_DEFAULT_WIDTH=$(CONFIG_DRM_DEFAULT_WIDTH)
endif

ifneq ($(CONFIG_DRM_DEFAULT_HEIGHT),)
  C_CONFIG += -DCONFIG_DRM_DEFAULT_HEIGHT=$(CONFIG_DRM_DEFAULT_HEIGHT)
endif

ifeq ($(CONFIG_AUDIO), y)
  C_CONFIG += -DCONFIG_AUDIO=1
else
  C_CONFIG += -DCONFIG_AUDIO=0
endif

ifeq ($(CONFIG_AUDIO_HDA), y)
  C_CONFIG += -DCONFIG_AUDIO_HDA=1
else
  C_CONFIG += -DCONFIG_AUDIO_HDA=0
endif

ifeq ($(CONFIG_AUDIO_SB16), y)
  C_CONFIG += -DCONFIG_AUDIO_SB16=1
else
  C_CONFIG += -DCONFIG_AUDIO_SB16=0
endif

ifeq ($(CONFIG_AUDIO_PCSPKR), y)
  C_CONFIG += -DCONFIG_AUDIO_PCSPKR=1
else
  C_CONFIG += -DCONFIG_AUDIO_PCSPKR=0
endif

ifneq ($(CONFIG_AUDIO_MAX_CARDS),)
  C_CONFIG += -DCONFIG_AUDIO_MAX_CARDS=$(CONFIG_AUDIO_MAX_CARDS)
endif

ifeq ($(CONFIG_I2C), y)
  C_CONFIG += -DCONFIG_I2C=1
else
  C_CONFIG += -DCONFIG_I2C=0
endif

ifneq ($(CONFIG_I2C_MAX_ADAPTERS),)
  C_CONFIG += -DCONFIG_I2C_MAX_ADAPTERS=$(CONFIG_I2C_MAX_ADAPTERS)
endif

ifeq ($(CONFIG_TPM), y)
  C_CONFIG += -DCONFIG_TPM=1
else
  C_CONFIG += -DCONFIG_TPM=0
endif

ifeq ($(CONFIG_SYSFS), y)
  C_CONFIG += -DCONFIG_SYSFS=1
else
  C_CONFIG += -DCONFIG_SYSFS=0
endif

ifeq ($(CONFIG_DEVTMPFS_MOUNT), y)
  C_CONFIG += -DCONFIG_DEVTMPFS_MOUNT=1
else
  C_CONFIG += -DCONFIG_DEVTMPFS_MOUNT=0
endif

ifeq ($(CONFIG_NTFS_FS), y)
  C_CONFIG += -DCONFIG_NTFS_FS=1
else
  C_CONFIG += -DCONFIG_NTFS_FS=0
endif

ifeq ($(CONFIG_FAT_FS), y)
  C_CONFIG += -DCONFIG_FAT_FS=1
else
  C_CONFIG += -DCONFIG_FAT_FS=0
endif

ifeq ($(CONFIG_ISO9660_FS), y)
  C_CONFIG += -DCONFIG_ISO9660_FS=1
else
  C_CONFIG += -DCONFIG_ISO9660_FS=0
endif

ifeq ($(CONFIG_EXTFS), y)
  C_CONFIG += -DCONFIG_EXTFS=1
else
  C_CONFIG += -DCONFIG_EXTFS=0
endif

ifeq ($(CONFIG_CGROUP), y)
  C_CONFIG += -DCONFIG_CGROUP=1
else
  C_CONFIG += -DCONFIG_CGROUP=0
endif

ifeq ($(CONFIG_MODULES), y)
  C_CONFIG += -DCONFIG_MODULES=1
else
  C_CONFIG += -DCONFIG_MODULES=0
endif

ifeq ($(CONFIG_MODULE_FORCE_LOAD), y)
  C_CONFIG += -DCONFIG_MODULE_FORCE_LOAD=1
else
  C_CONFIG += -DCONFIG_MODULE_FORCE_LOAD=0
endif

ifeq ($(CONFIG_MODULE_FORCE_UNLOAD), y)
  C_CONFIG += -DCONFIG_MODULE_FORCE_UNLOAD=1
else
  C_CONFIG += -DCONFIG_MODULE_FORCE_UNLOAD=0
endif

ifeq ($(CONFIG_MODULE_SIG_FORCE), y)
  C_CONFIG += -DCONFIG_MODULE_SIG_FORCE=1
else
  C_CONFIG += -DCONFIG_MODULE_SIG_FORCE=0
endif

ifneq ($(CONFIG_MODULE_MAX_SIZE),)
  C_CONFIG += -DCONFIG_MODULE_MAX_SIZE=$(CONFIG_MODULE_MAX_SIZE)
endif

ifneq ($(CONFIG_EPOLL_MAX_EVENTS),)
  C_CONFIG += -DCONFIG_EPOLL_MAX_EVENTS=$(CONFIG_EPOLL_MAX_EVENTS)
endif

ifneq ($(CONFIG_EPOLL_MAX_NESTS),)
  C_CONFIG += -DCONFIG_EPOLL_MAX_NESTS=$(CONFIG_EPOLL_MAX_NESTS)
endif

ifneq ($(CONFIG_FUTEX_WAITV_MAX),)
  C_CONFIG += -DCONFIG_FUTEX_WAITV_MAX=$(CONFIG_FUTEX_WAITV_MAX)
endif

ifneq ($(CONFIG_PIPE_ATOMIC_SIZE),)
  C_CONFIG += -DCONFIG_PIPE_ATOMIC_SIZE=$(CONFIG_PIPE_ATOMIC_SIZE)
endif

ifneq ($(CONFIG_MQ_MAXMSG_DEFAULT),)
  C_CONFIG += -DCONFIG_MQ_MAXMSG_DEFAULT=$(CONFIG_MQ_MAXMSG_DEFAULT)
endif

ifneq ($(CONFIG_MQ_MAXMSG_MAX),)
  C_CONFIG += -DCONFIG_MQ_MAXMSG_MAX=$(CONFIG_MQ_MAXMSG_MAX)
endif

ifneq ($(CONFIG_MQ_MSGSIZE_DEFAULT),)
  C_CONFIG += -DCONFIG_MQ_MSGSIZE_DEFAULT=$(CONFIG_MQ_MSGSIZE_DEFAULT)
endif

ifneq ($(CONFIG_MQ_MSGSIZE_MAX),)
  C_CONFIG += -DCONFIG_MQ_MSGSIZE_MAX=$(CONFIG_MQ_MSGSIZE_MAX)
endif

ifneq ($(CONFIG_MQ_MAX_QUEUES),)
  C_CONFIG += -DCONFIG_MQ_MAX_QUEUES=$(CONFIG_MQ_MAX_QUEUES)
endif

ifneq ($(CONFIG_MQ_NAME_MAX),)
  C_CONFIG += -DCONFIG_MQ_NAME_MAX=$(CONFIG_MQ_NAME_MAX)
endif

ifneq ($(CONFIG_MQ_PRIO_MAX),)
  C_CONFIG += -DCONFIG_MQ_PRIO_MAX=$(CONFIG_MQ_PRIO_MAX)
endif

ifneq ($(CONFIG_MSGMAX),)
  C_CONFIG += -DCONFIG_MSGMAX=$(CONFIG_MSGMAX)
endif

ifneq ($(CONFIG_MSG_MAX_QUEUES),)
  C_CONFIG += -DCONFIG_MSG_MAX_QUEUES=$(CONFIG_MSG_MAX_QUEUES)
endif

ifneq ($(CONFIG_SEM_MAX_NSEMS),)
  C_CONFIG += -DCONFIG_SEM_MAX_NSEMS=$(CONFIG_SEM_MAX_NSEMS)
endif

ifneq ($(CONFIG_SEM_MAX_SETS),)
  C_CONFIG += -DCONFIG_SEM_MAX_SETS=$(CONFIG_SEM_MAX_SETS)
endif

ifneq ($(CONFIG_SHM_MAX_SEGS),)
  C_CONFIG += -DCONFIG_SHM_MAX_SEGS=$(CONFIG_SHM_MAX_SEGS)
endif

ifneq ($(CONFIG_PROCESS_MAX_ARGV),)
  C_CONFIG += -DCONFIG_PROCESS_MAX_ARGV=$(CONFIG_PROCESS_MAX_ARGV)
endif

ifneq ($(CONFIG_PROCESS_MAX_ENVP),)
  C_CONFIG += -DCONFIG_PROCESS_MAX_ENVP=$(CONFIG_PROCESS_MAX_ENVP)
endif

ifneq ($(CONFIG_PROCESS_MAX_GROUPS),)
  C_CONFIG += -DCONFIG_PROCESS_MAX_GROUPS=$(CONFIG_PROCESS_MAX_GROUPS)
endif

ifneq ($(CONFIG_PROCESS_HEAP_START),)
  C_CONFIG += -DCONFIG_PROCESS_HEAP_START=$(CONFIG_PROCESS_HEAP_START)
endif

ifneq ($(CONFIG_PROCESS_HEAP_MAX),)
  C_CONFIG += -DCONFIG_PROCESS_HEAP_MAX=$(CONFIG_PROCESS_HEAP_MAX)
endif

ifneq ($(CONFIG_TASK_DEFAULT_SLICE),)
  C_CONFIG += -DCONFIG_TASK_DEFAULT_SLICE=$(CONFIG_TASK_DEFAULT_SLICE)
endif

ifneq ($(CONFIG_SCHED_DOMAIN_MAX_LEVELS),)
  C_CONFIG += -DCONFIG_SCHED_DOMAIN_MAX_LEVELS=$(CONFIG_SCHED_DOMAIN_MAX_LEVELS)
endif

ifneq ($(CONFIG_BUDDY_MAX_ORDER),)
  C_CONFIG += -DCONFIG_BUDDY_MAX_ORDER=$(CONFIG_BUDDY_MAX_ORDER)
endif

ifneq ($(CONFIG_FRAME_PCP_BATCH),)
  C_CONFIG += -DCONFIG_FRAME_PCP_BATCH=$(CONFIG_FRAME_PCP_BATCH)
endif

ifneq ($(CONFIG_FRAME_PCP_HIGH),)
  C_CONFIG += -DCONFIG_FRAME_PCP_HIGH=$(CONFIG_FRAME_PCP_HIGH)
endif

ifneq ($(CONFIG_FRAME_RECLAIM_BATCH),)
  C_CONFIG += -DCONFIG_FRAME_RECLAIM_BATCH=$(CONFIG_FRAME_RECLAIM_BATCH)
endif

ifneq ($(CONFIG_FRAME_PCP_MAX_CPUS),)
  C_CONFIG += -DCONFIG_FRAME_PCP_MAX_CPUS=$(CONFIG_FRAME_PCP_MAX_CPUS)
endif

ifneq ($(CONFIG_SLAB_MAX_ORDER),)
  C_CONFIG += -DCONFIG_SLAB_MAX_ORDER=$(CONFIG_SLAB_MAX_ORDER)
endif

ifneq ($(CONFIG_HEAP_MIN_ALIGNMENT),)
  C_CONFIG += -DCONFIG_HEAP_MIN_ALIGNMENT=$(CONFIG_HEAP_MIN_ALIGNMENT)
endif

ifneq ($(CONFIG_NETDEV_MAX),)
  C_CONFIG += -DCONFIG_NETDEV_MAX=$(CONFIG_NETDEV_MAX)
endif

ifneq ($(CONFIG_NETDEV_MTU_MAX),)
  C_CONFIG += -DCONFIG_NETDEV_MTU_MAX=$(CONFIG_NETDEV_MTU_MAX)
endif

ifneq ($(CONFIG_NETDEV_NAME_MAX),)
  C_CONFIG += -DCONFIG_NETDEV_NAME_MAX=$(CONFIG_NETDEV_NAME_MAX)
endif

ifneq ($(CONFIG_NETDEV_DNS_MAX),)
  C_CONFIG += -DCONFIG_NETDEV_DNS_MAX=$(CONFIG_NETDEV_DNS_MAX)
endif

ifneq ($(CONFIG_SOCK_BUF_MAX),)
  C_CONFIG += -DCONFIG_SOCK_BUF_MAX=$(CONFIG_SOCK_BUF_MAX)
endif

ifneq ($(CONFIG_SOCK_RIGHTS_MAX),)
  C_CONFIG += -DCONFIG_SOCK_RIGHTS_MAX=$(CONFIG_SOCK_RIGHTS_MAX)
endif

ifneq ($(CONFIG_SOCK_BOUND_MAX),)
  C_CONFIG += -DCONFIG_SOCK_BOUND_MAX=$(CONFIG_SOCK_BOUND_MAX)
endif

ifneq ($(CONFIG_LOOPBACK_QUEUE_MAX),)
  C_CONFIG += -DCONFIG_LOOPBACK_QUEUE_MAX=$(CONFIG_LOOPBACK_QUEUE_MAX)
endif

ifneq ($(CONFIG_LOOPBACK_BYTES_MAX),)
  C_CONFIG += -DCONFIG_LOOPBACK_BYTES_MAX=$(CONFIG_LOOPBACK_BYTES_MAX)
endif

ifneq ($(CONFIG_ARP_CACHE_CAPACITY),)
  C_CONFIG += -DCONFIG_ARP_CACHE_CAPACITY=$(CONFIG_ARP_CACHE_CAPACITY)
endif

ifneq ($(CONFIG_ARP_MAX_RETRIES),)
  C_CONFIG += -DCONFIG_ARP_MAX_RETRIES=$(CONFIG_ARP_MAX_RETRIES)
endif

ifneq ($(CONFIG_ARP_PENDING_TOTAL),)
  C_CONFIG += -DCONFIG_ARP_PENDING_TOTAL=$(CONFIG_ARP_PENDING_TOTAL)
endif

ifneq ($(CONFIG_NDP_CACHE_CAPACITY),)
  C_CONFIG += -DCONFIG_NDP_CACHE_CAPACITY=$(CONFIG_NDP_CACHE_CAPACITY)
endif

ifneq ($(CONFIG_NDP_MAX_RETRIES),)
  C_CONFIG += -DCONFIG_NDP_MAX_RETRIES=$(CONFIG_NDP_MAX_RETRIES)
endif

ifneq ($(CONFIG_NDP_PENDING_TOTAL),)
  C_CONFIG += -DCONFIG_NDP_PENDING_TOTAL=$(CONFIG_NDP_PENDING_TOTAL)
endif

ifneq ($(CONFIG_TCP_ENDPOINT_MAX),)
  C_CONFIG += -DCONFIG_TCP_ENDPOINT_MAX=$(CONFIG_TCP_ENDPOINT_MAX)
endif

ifneq ($(CONFIG_TCP_ACCEPT_MAX),)
  C_CONFIG += -DCONFIG_TCP_ACCEPT_MAX=$(CONFIG_TCP_ACCEPT_MAX)
endif

ifneq ($(CONFIG_TCP_RX_BUFFER_MAX),)
  C_CONFIG += -DCONFIG_TCP_RX_BUFFER_MAX=$(CONFIG_TCP_RX_BUFFER_MAX)
endif

ifneq ($(CONFIG_TCP_OOO_SEGMENT_MAX),)
  C_CONFIG += -DCONFIG_TCP_OOO_SEGMENT_MAX=$(CONFIG_TCP_OOO_SEGMENT_MAX)
endif

ifneq ($(CONFIG_TCP_TX_SEGMENT_MAX),)
  C_CONFIG += -DCONFIG_TCP_TX_SEGMENT_MAX=$(CONFIG_TCP_TX_SEGMENT_MAX)
endif

ifneq ($(CONFIG_UDP_ENDPOINT_MAX),)
  C_CONFIG += -DCONFIG_UDP_ENDPOINT_MAX=$(CONFIG_UDP_ENDPOINT_MAX)
endif

ifneq ($(CONFIG_UDP_RX_QUEUE_MAX),)
  C_CONFIG += -DCONFIG_UDP_RX_QUEUE_MAX=$(CONFIG_UDP_RX_QUEUE_MAX)
endif

ifneq ($(CONFIG_UDP_RX_BYTES_MAX),)
  C_CONFIG += -DCONFIG_UDP_RX_BYTES_MAX=$(CONFIG_UDP_RX_BYTES_MAX)
endif

ifneq ($(CONFIG_ICMP_ENDPOINT_MAX),)
  C_CONFIG += -DCONFIG_ICMP_ENDPOINT_MAX=$(CONFIG_ICMP_ENDPOINT_MAX)
endif

ifneq ($(CONFIG_ICMP_RX_QUEUE_MAX),)
  C_CONFIG += -DCONFIG_ICMP_RX_QUEUE_MAX=$(CONFIG_ICMP_RX_QUEUE_MAX)
endif

ifneq ($(CONFIG_ICMP_RX_BYTES_MAX),)
  C_CONFIG += -DCONFIG_ICMP_RX_BYTES_MAX=$(CONFIG_ICMP_RX_BYTES_MAX)
endif

ifneq ($(CONFIG_IPV4_REASSEMBLY_SLOTS),)
  C_CONFIG += -DCONFIG_IPV4_REASSEMBLY_SLOTS=$(CONFIG_IPV4_REASSEMBLY_SLOTS)
endif

ifneq ($(CONFIG_IPV6_REASSEMBLY_SLOTS),)
  C_CONFIG += -DCONFIG_IPV6_REASSEMBLY_SLOTS=$(CONFIG_IPV6_REASSEMBLY_SLOTS)
endif

ifneq ($(CONFIG_NETLINK_MAX),)
  C_CONFIG += -DCONFIG_NETLINK_MAX=$(CONFIG_NETLINK_MAX)
endif

ifneq ($(CONFIG_NL_RECV_QUEUE_MAX),)
  C_CONFIG += -DCONFIG_NL_RECV_QUEUE_MAX=$(CONFIG_NL_RECV_QUEUE_MAX)
endif

ifneq ($(CONFIG_RTMSG_BUF_SIZE),)
  C_CONFIG += -DCONFIG_RTMSG_BUF_SIZE=$(CONFIG_RTMSG_BUF_SIZE)
endif

ifneq ($(CONFIG_NL_BROADCAST_MAX),)
  C_CONFIG += -DCONFIG_NL_BROADCAST_MAX=$(CONFIG_NL_BROADCAST_MAX)
endif

ifneq ($(CONFIG_VFS_PATH_MAX),)
  C_CONFIG += -DCONFIG_VFS_PATH_MAX=$(CONFIG_VFS_PATH_MAX)
endif

ifneq ($(CONFIG_DEVTMPFS_MAX_DEVICES),)
  C_CONFIG += -DCONFIG_DEVTMPFS_MAX_DEVICES=$(CONFIG_DEVTMPFS_MAX_DEVICES)
endif

ifneq ($(CONFIG_VFS_DCACHE_BUCKETS),)
  C_CONFIG += -DCONFIG_VFS_DCACHE_BUCKETS=$(CONFIG_VFS_DCACHE_BUCKETS)
endif

ifneq ($(CONFIG_VFS_DCACHE_MAX_NEGATIVE),)
  C_CONFIG += -DCONFIG_VFS_DCACHE_MAX_NEGATIVE=$(CONFIG_VFS_DCACHE_MAX_NEGATIVE)
endif

ifneq ($(CONFIG_VFS_ICACHE_BUCKETS),)
  C_CONFIG += -DCONFIG_VFS_ICACHE_BUCKETS=$(CONFIG_VFS_ICACHE_BUCKETS)
endif

ifneq ($(CONFIG_VFS_ICACHE_MAX_UNUSED),)
  C_CONFIG += -DCONFIG_VFS_ICACHE_MAX_UNUSED=$(CONFIG_VFS_ICACHE_MAX_UNUSED)
endif

ifneq ($(CONFIG_PAGECACHE_HASH_MAX_BITS),)
  C_CONFIG += -DCONFIG_PAGECACHE_HASH_MAX_BITS=$(CONFIG_PAGECACHE_HASH_MAX_BITS)
endif

ifneq ($(CONFIG_PAGECACHE_READAHEAD_MAX),)
  C_CONFIG += -DCONFIG_PAGECACHE_READAHEAD_MAX=$(CONFIG_PAGECACHE_READAHEAD_MAX)
endif

ifneq ($(CONFIG_PAGECACHE_RECLAIM_MAX_WRITEBACK),)
  C_CONFIG += -DCONFIG_PAGECACHE_RECLAIM_MAX_WRITEBACK=$(CONFIG_PAGECACHE_RECLAIM_MAX_WRITEBACK)
endif

ifneq ($(CONFIG_POLL_NFDS_MAX),)
  C_CONFIG += -DCONFIG_POLL_NFDS_MAX=$(CONFIG_POLL_NFDS_MAX)
endif

ifneq ($(CONFIG_SELECT_NFDS_MAX),)
  C_CONFIG += -DCONFIG_SELECT_NFDS_MAX=$(CONFIG_SELECT_NFDS_MAX)
endif

ifneq ($(CONFIG_SIGQUEUE_MAX),)
  C_CONFIG += -DCONFIG_SIGQUEUE_MAX=$(CONFIG_SIGQUEUE_MAX)
endif

ifneq ($(CONFIG_SECCOMP_MAX_INSNS_PER_FILTER),)
  C_CONFIG += -DCONFIG_SECCOMP_MAX_INSNS_PER_FILTER=$(CONFIG_SECCOMP_MAX_INSNS_PER_FILTER)
endif

ifneq ($(CONFIG_NMI_LOG_MAX_CPUS),)
  C_CONFIG += -DCONFIG_NMI_LOG_MAX_CPUS=$(CONFIG_NMI_LOG_MAX_CPUS)
endif

ifneq ($(CONFIG_LOG_MAX_LENGTH),)
  C_CONFIG += -DCONFIG_LOG_MAX_LENGTH=$(CONFIG_LOG_MAX_LENGTH)
endif

ifneq ($(CONFIG_LOG_BUFFER_SIZE),)
  C_CONFIG += -DCONFIG_LOG_BUFFER_SIZE=$(CONFIG_LOG_BUFFER_SIZE)
endif

ifneq ($(CONFIG_UEVENT_BUFFER_SIZE),)
  C_CONFIG += -DCONFIG_UEVENT_BUFFER_SIZE=$(CONFIG_UEVENT_BUFFER_SIZE)
endif

ifneq ($(CONFIG_UEVENT_NUM_ENVP),)
  C_CONFIG += -DCONFIG_UEVENT_NUM_ENVP=$(CONFIG_UEVENT_NUM_ENVP)
endif

ifneq ($(CONFIG_ACPI_MAX_GPE_HANDLERS),)
  C_CONFIG += -DCONFIG_ACPI_MAX_GPE_HANDLERS=$(CONFIG_ACPI_MAX_GPE_HANDLERS)
endif

ifneq ($(CONFIG_MODULE_NAME_LEN),)
  C_CONFIG += -DCONFIG_MODULE_NAME_LEN=$(CONFIG_MODULE_NAME_LEN)
endif

ifneq ($(CONFIG_MODULE_PARAM_MAX),)
  C_CONFIG += -DCONFIG_MODULE_PARAM_MAX=$(CONFIG_MODULE_PARAM_MAX)
endif

ifneq ($(CONFIG_SWAP_MAX_AREAS),)
  C_CONFIG += -DCONFIG_SWAP_MAX_AREAS=$(CONFIG_SWAP_MAX_AREAS)
endif

ifneq ($(CONFIG_TCP_DATA_RETRIES_DEFAULT),)
  C_CONFIG += -DCONFIG_TCP_DATA_RETRIES_DEFAULT=$(CONFIG_TCP_DATA_RETRIES_DEFAULT)
endif

ifneq ($(CONFIG_TCP_SYN_RETRIES_DEFAULT),)
  C_CONFIG += -DCONFIG_TCP_SYN_RETRIES_DEFAULT=$(CONFIG_TCP_SYN_RETRIES_DEFAULT)
endif

ifneq ($(CONFIG_UART_RX_BUF_SIZE),)
  C_CONFIG += -DCONFIG_UART_RX_BUF_SIZE=$(CONFIG_UART_RX_BUF_SIZE)
endif

ifneq ($(CONFIG_UART_TX_BUF_SIZE),)
  C_CONFIG += -DCONFIG_UART_TX_BUF_SIZE=$(CONFIG_UART_TX_BUF_SIZE)
endif

ifeq ($(CONFIG_NUMA), y)
  C_CONFIG += -DCONFIG_NUMA=1
else
  C_CONFIG += -DCONFIG_NUMA=0
endif

ifneq ($(CONFIG_NUMA_MAX_NODES),)
  C_CONFIG += -DCONFIG_NUMA_MAX_NODES=$(CONFIG_NUMA_MAX_NODES)
endif

ifneq ($(CONFIG_NUMA_MAX_RANGES),)
  C_CONFIG += -DCONFIG_NUMA_MAX_RANGES=$(CONFIG_NUMA_MAX_RANGES)
endif

ifneq ($(CONFIG_SCHED_MAX_CPUS),)
  C_CONFIG += -DCONFIG_SCHED_MAX_CPUS=$(CONFIG_SCHED_MAX_CPUS)
endif
