# =====================================================
#
#      kconfig.mk
#      Uinxed-Kernel kconfig script
#
#      2026/8/12 By MicroFish
#      Copyright (C) 2020 ViudiraTech, based on the Apache 2.0 license.
#
# =====================================================

ifeq ($(CONFIG_KERNEL_LOG), y)
  C_CONFIG += -DKERNEL_LOG=1
else
  C_CONFIG += -DKERNEL_LOG=0
endif

ifneq ($(CONFIG_TTY_DEFAULT_DEV),)
  C_CONFIG += -DTTY_DEFAULT_DEV=\"$(CONFIG_TTY_DEFAULT_DEV)\"
endif

ifeq ($(CONFIG_VT), y)
  C_CONFIG += -DCONFIG_VT=1
else
  C_CONFIG += -DCONFIG_VT=0
endif

ifneq ($(CONFIG_VT_COUNT),)
  C_CONFIG += -DCONFIG_VT_COUNT=$(CONFIG_VT_COUNT)
endif

ifneq ($(CONFIG_TTY_BUF_SIZE),)
  C_CONFIG += -DTTY_BUF_SIZE=$(CONFIG_TTY_BUF_SIZE)
endif

ifneq ($(CONFIG_TTY_CORE_BUFFER_SIZE),)
  C_CONFIG += -DTTY_CORE_BUFFER_SIZE=$(CONFIG_TTY_CORE_BUFFER_SIZE)
endif

ifeq ($(CONFIG_UNIX98_PTYS),)
  C_CONFIG += -DCONFIG_UNIX98_PTYS=1
else ifeq ($(CONFIG_UNIX98_PTYS), y)
  C_CONFIG += -DCONFIG_UNIX98_PTYS=1
else
  C_CONFIG += -DCONFIG_UNIX98_PTYS=0
endif

ifeq ($(CONFIG_UNIX98_PTY_MAX),)
  C_CONFIG += -DCONFIG_UNIX98_PTY_MAX=64
else
  C_CONFIG += -DCONFIG_UNIX98_PTY_MAX=$(CONFIG_UNIX98_PTY_MAX)
endif

ifneq ($(CONFIG_SERIAL_BAUD_RATE),)
  C_CONFIG += -DSERIAL_BAUD_RATE=$(CONFIG_SERIAL_BAUD_RATE)
endif

ifneq ($(CONFIG_SERIAL_DATA_BITS),)
  C_CONFIG += -DSERIAL_DATA_BITS=$(CONFIG_SERIAL_DATA_BITS)
endif

ifneq ($(CONFIG_SERIAL_STOP_BITS),)
  C_CONFIG += -DSERIAL_STOP_BITS=$(CONFIG_SERIAL_STOP_BITS)
endif

ifeq ($(CONFIG_SERIAL),)
  C_CONFIG += -DCONFIG_SERIAL=1
else ifeq ($(CONFIG_SERIAL), y)
  C_CONFIG += -DCONFIG_SERIAL=1
else
  C_CONFIG += -DCONFIG_SERIAL=0
endif

ifneq ($(CONFIG_CPU_MAX_COUNT),)
  C_CONFIG += -DCPU_MAX_COUNT=$(CONFIG_CPU_MAX_COUNT)
endif

# Kernel code must not emit FPU/SSE/AVX instructions implicitly: any
# kernel floating-point use must opt in per-file (or per-function) with
# `#pragma GCC target("sse2")` and be wrapped in kernel_fpu_begin()/
# kernel_fpu_end() (see include/arch/fpu.h).
ifeq ($(CONFIG_CPU_FEATURE_FPU), y)
  C_CONFIG += -DCPU_FEATURE_FPU=1
else
  C_CONFIG += -DCPU_FEATURE_FPU=0
endif

ifeq ($(CONFIG_CPU_FEATURE_SSE), y)
  C_CONFIG += -DCPU_FEATURE_SSE=1
else
  C_CONFIG += -DCPU_FEATURE_SSE=0
endif

ifeq ($(CONFIG_CPU_FEATURE_AVX), y)
  C_CONFIG += -DCPU_FEATURE_AVX=1
else
  C_CONFIG += -DCPU_FEATURE_AVX=0
endif

ifeq ($(CONFIG_CPU_FEATURE_AVX512), y)
  C_CONFIG += -DCPU_FEATURE_AVX512=1
else
  C_CONFIG += -DCPU_FEATURE_AVX512=0
endif

ifneq ($(CONFIG_KERNEL_HEAP_MAX_SIZE),)
  C_CONFIG += -DKERNEL_HEAP_MAX_MIB=$(CONFIG_KERNEL_HEAP_MAX_SIZE)
endif

ifneq ($(CONFIG_TIMER_HZ),)
  C_CONFIG += -DTIMER_HZ=$(CONFIG_TIMER_HZ)
endif

ifneq ($(CONFIG_SCHED_BASE_SLICE),)
  C_CONFIG += -DSCHED_BASE_SLICE=$(CONFIG_SCHED_BASE_SLICE)
endif

ifneq ($(CONFIG_SCHED_LATENCY),)
  C_CONFIG += -DSCHED_LATENCY=$(CONFIG_SCHED_LATENCY)
endif

ifneq ($(CONFIG_SCHED_MIN_GRANULARITY),)
  C_CONFIG += -DSCHED_MIN_GRANULARITY=$(CONFIG_SCHED_MIN_GRANULARITY)
endif

ifneq ($(CONFIG_SCHED_WAKEUP_GRANULARITY),)
  C_CONFIG += -DSCHED_WAKEUP_GRANULARITY=$(CONFIG_SCHED_WAKEUP_GRANULARITY)
endif

ifneq ($(CONFIG_SCHED_LOAD_BALANCE_INTERVAL),)
  C_CONFIG += -DSCHED_LOAD_BALANCE_INTERVAL=$(CONFIG_SCHED_LOAD_BALANCE_INTERVAL)
endif

ifneq ($(CONFIG_SCHED_BALANCE_BATCH),)
  C_CONFIG += -DSCHED_BALANCE_BATCH=$(CONFIG_SCHED_BALANCE_BATCH)
endif

ifneq ($(CONFIG_SCHED_MIGRATION_COOLDOWN),)
  C_CONFIG += -DSCHED_MIGRATION_COOLDOWN=$(CONFIG_SCHED_MIGRATION_COOLDOWN)
endif

ifneq ($(CONFIG_PROCESS_MAX_FD),)
  C_CONFIG += -DPROCESS_MAX_FD=$(CONFIG_PROCESS_MAX_FD)
endif

ifneq ($(CONFIG_PROCESS_TABLE_SIZE),)
  C_CONFIG += -DPROCESS_TABLE_SIZE=$(CONFIG_PROCESS_TABLE_SIZE)
endif

ifneq ($(CONFIG_PROCESS_KERNEL_STACK_SIZE),)
  C_CONFIG += -DPROCESS_KERNEL_STACK=$(CONFIG_PROCESS_KERNEL_STACK_SIZE)
endif

ifneq ($(CONFIG_PROCESS_USER_STACK_SIZE),)
  C_CONFIG += -DPROCESS_STACK_SIZE=$(CONFIG_PROCESS_USER_STACK_SIZE)
endif

ifeq ($(CONFIG_INIT_MODULE), y)
  C_CONFIG += -DCONFIG_INIT_MODULE=1
else
  C_CONFIG += -DCONFIG_INIT_MODULE=0
endif

ifneq ($(CONFIG_INIT_PATH),)
  C_CONFIG += -DCONFIG_INIT_PATH=\"$(CONFIG_INIT_PATH)\"
endif

ifneq ($(CONFIG_PIPE_BUF_SIZE),)
  C_CONFIG += -DPIPE_BUF_SIZE=$(CONFIG_PIPE_BUF_SIZE)
endif

ifneq ($(CONFIG_PIPE_ADAPTIVE_SPIN_ITERS),)
  C_CONFIG += -DPIPE_ADAPTIVE_SPIN_ITERS=$(CONFIG_PIPE_ADAPTIVE_SPIN_ITERS)
endif

ifneq ($(CONFIG_SOCKET_BUF_SIZE),)
  C_CONFIG += -DSOCK_BUF_SIZE=$(CONFIG_SOCKET_BUF_SIZE)
endif

ifneq ($(CONFIG_SOCKET_ACCEPT_QUEUE_MAX),)
  C_CONFIG += -DSOCK_ACCEPT_QUEUE_MAX=$(CONFIG_SOCKET_ACCEPT_QUEUE_MAX)
endif

ifneq ($(CONFIG_EPOLL_MAX_FDS),)
  C_CONFIG += -DEPOLL_MAX_FDS=$(CONFIG_EPOLL_MAX_FDS)
endif

ifneq ($(CONFIG_FUTEX_HASH_BITS),)
  C_CONFIG += -DFUTEX_HASH_BITS=$(CONFIG_FUTEX_HASH_BITS)
endif

ifneq ($(CONFIG_INOTIFY_MAX_QUEUED_EVENTS),)
  C_CONFIG += -DINOTIFY_MAX_QUEUED_EVENTS=$(CONFIG_INOTIFY_MAX_QUEUED_EVENTS)
endif

ifneq ($(CONFIG_INOTIFY_MAX_USER_INSTANCES),)
  C_CONFIG += -DINOTIFY_MAX_USER_INSTANCES=$(CONFIG_INOTIFY_MAX_USER_INSTANCES)
endif

ifneq ($(CONFIG_INOTIFY_MAX_USER_WATCHES),)
  C_CONFIG += -DINOTIFY_MAX_USER_WATCHES=$(CONFIG_INOTIFY_MAX_USER_WATCHES)
endif

ifeq ($(CONFIG_NETLINK), y)
  C_CONFIG += -DCONFIG_NETLINK=1
else
  C_CONFIG += -DCONFIG_NETLINK=0
endif

ifeq ($(CONFIG_SYSVIPC), y)
  C_CONFIG += -DCONFIG_SYSVIPC=1
else
  C_CONFIG += -DCONFIG_SYSVIPC=0
endif

ifeq ($(CONFIG_POSIX_MQ), y)
  C_CONFIG += -DCONFIG_POSIX_MQ=1
else
  C_CONFIG += -DCONFIG_POSIX_MQ=0
endif

ifeq ($(CONFIG_NET), y)
  C_CONFIG += -DCONFIG_NET=1
else
  C_CONFIG += -DCONFIG_NET=0
endif

ifeq ($(CONFIG_INET), y)
  C_CONFIG += -DCONFIG_INET=1
else
  C_CONFIG += -DCONFIG_INET=0
endif

ifeq ($(CONFIG_E1000), y)
  C_CONFIG += -DCONFIG_E1000=1
else
  C_CONFIG += -DCONFIG_E1000=0
endif

ifeq ($(CONFIG_RTL8169), y)
  C_CONFIG += -DCONFIG_RTL8169=1
else
  C_CONFIG += -DCONFIG_RTL8169=0
endif

ifeq ($(CONFIG_RTL8139), y)
  C_CONFIG += -DCONFIG_RTL8139=1
else
  C_CONFIG += -DCONFIG_RTL8139=0
endif

ifeq ($(CONFIG_PS2_KEYBOARD_MOUSE), y)
  C_CONFIG += -DCONFIG_PS2_KEYBOARD_MOUSE=1
else
  C_CONFIG += -DCONFIG_PS2_KEYBOARD_MOUSE=0
endif

ifeq ($(CONFIG_PARPORT), y)
  C_CONFIG += -DCONFIG_PARPORT=1
else
  C_CONFIG += -DCONFIG_PARPORT=0
endif

ifeq ($(CONFIG_ATA), y)
  C_CONFIG += -DCONFIG_ATA=1
else
  C_CONFIG += -DCONFIG_ATA=0
endif

ifeq ($(CONFIG_NVME), y)
  C_CONFIG += -DCONFIG_NVME=1
else
  C_CONFIG += -DCONFIG_NVME=0
endif

ifeq ($(CONFIG_SWAP), y)
  C_CONFIG += -DCONFIG_SWAP=1
else
  C_CONFIG += -DCONFIG_SWAP=0
endif

ifeq ($(CONFIG_INPUT_EVDEV), y)
  C_CONFIG += -DCONFIG_INPUT_EVDEV=1
else
  C_CONFIG += -DCONFIG_INPUT_EVDEV=0
endif

ifneq ($(CONFIG_INPUT_EVDEV_BUFSIZE),)
  C_CONFIG += -DINPUT_EVDEV_BUFSIZE=$(CONFIG_INPUT_EVDEV_BUFSIZE)
endif

ifeq ($(CONFIG_USB), y)
  C_CONFIG += -DCONFIG_USB=1
else
  C_CONFIG += -DCONFIG_USB=0
endif

ifeq ($(CONFIG_USB_UHCI), y)
  C_CONFIG += -DCONFIG_USB_UHCI=1
else
  C_CONFIG += -DCONFIG_USB_UHCI=0
endif

ifeq ($(CONFIG_USB_OHCI), y)
  C_CONFIG += -DCONFIG_USB_OHCI=1
else
  C_CONFIG += -DCONFIG_USB_OHCI=0
endif

ifeq ($(CONFIG_USB_EHCI), y)
  C_CONFIG += -DCONFIG_USB_EHCI=1
else
  C_CONFIG += -DCONFIG_USB_EHCI=0
endif

ifeq ($(CONFIG_USB_XHCI), y)
  C_CONFIG += -DCONFIG_USB_XHCI=1
else
  C_CONFIG += -DCONFIG_USB_XHCI=0
endif

ifeq ($(CONFIG_USB_HID), y)
  C_CONFIG += -DCONFIG_USB_HID=1
else
  C_CONFIG += -DCONFIG_USB_HID=0
endif

ifeq ($(CONFIG_USB_STORAGE), y)
  C_CONFIG += -DCONFIG_USB_STORAGE=1
else
  C_CONFIG += -DCONFIG_USB_STORAGE=0
endif

ifeq ($(CONFIG_DRM), y)
  C_CONFIG += -DCONFIG_DRM=1
else
  C_CONFIG += -DCONFIG_DRM=0
endif

ifeq ($(CONFIG_BOOT_LOGO), y)
  C_CONFIG += -DBOOT_LOGO=1
else
  C_CONFIG += -DBOOT_LOGO=0
endif

ifeq ($(CONFIG_VIRTIO), y)
  C_CONFIG += -DCONFIG_VIRTIO=1
else
  C_CONFIG += -DCONFIG_VIRTIO=0
endif

ifeq ($(CONFIG_VIRTIO_GPU), y)
  C_CONFIG += -DCONFIG_VIRTIO_GPU=1
else
  C_CONFIG += -DCONFIG_VIRTIO_GPU=0
endif

ifneq ($(CONFIG_DRM_DEFAULT_WIDTH),)
  C_CONFIG += -DCONFIG_DRM_DEFAULT_WIDTH=$(CONFIG_DRM_DEFAULT_WIDTH)
endif

ifneq ($(CONFIG_DRM_DEFAULT_HEIGHT),)
  C_CONFIG += -DCONFIG_DRM_DEFAULT_HEIGHT=$(CONFIG_DRM_DEFAULT_HEIGHT)
endif

ifeq ($(CONFIG_SOUND_HDA), y)
  C_CONFIG += -DCONFIG_SOUND_HDA=1
else
  C_CONFIG += -DCONFIG_SOUND_HDA=0
endif

ifeq ($(CONFIG_SOUND_SB16), y)
  C_CONFIG += -DCONFIG_SOUND_SB16=1
else
  C_CONFIG += -DCONFIG_SOUND_SB16=0
endif

ifeq ($(CONFIG_PCSPKR), y)
  C_CONFIG += -DCONFIG_PCSPKR=1
else
  C_CONFIG += -DCONFIG_PCSPKR=0
endif

ifeq ($(CONFIG_I2C), y)
  C_CONFIG += -DCONFIG_I2C=1
else
  C_CONFIG += -DCONFIG_I2C=0
endif

ifeq ($(CONFIG_TPM), y)
  C_CONFIG += -DCONFIG_TPM=1
else
  C_CONFIG += -DCONFIG_TPM=0
endif

ifeq ($(CONFIG_SYSFS), y)
  C_CONFIG += -DCONFIG_SYSFS=1
else
  C_CONFIG += -DCONFIG_SYSFS=0
endif

ifeq ($(CONFIG_DEVTMPFS_MOUNT), y)
  C_CONFIG += -DCONFIG_DEVTMPFS_MOUNT=1
else
  C_CONFIG += -DCONFIG_DEVTMPFS_MOUNT=0
endif

ifeq ($(CONFIG_UEVENT_HELPER), y)
  C_CONFIG += -DCONFIG_UEVENT_HELPER=1
else
  C_CONFIG += -DCONFIG_UEVENT_HELPER=0
endif

ifeq ($(CONFIG_NTFS_FS), y)
  C_CONFIG += -DCONFIG_NTFS_FS=1
else
  C_CONFIG += -DCONFIG_NTFS_FS=0
endif

ifeq ($(CONFIG_FAT_FS), y)
  C_CONFIG += -DCONFIG_FAT_FS=1
else
  C_CONFIG += -DCONFIG_FAT_FS=0
endif

ifeq ($(CONFIG_ISO9660_FS), y)
  C_CONFIG += -DCONFIG_ISO9660_FS=1
else
  C_CONFIG += -DCONFIG_ISO9660_FS=0
endif

ifeq ($(CONFIG_EXTFS), y)
  C_CONFIG += -DCONFIG_EXTFS=1
else
  C_CONFIG += -DCONFIG_EXTFS=0
endif

ifeq ($(CONFIG_CGROUP), y)
  C_CONFIG += -DCONFIG_CGROUP=1
else
  C_CONFIG += -DCONFIG_CGROUP=0
endif

ifeq ($(CONFIG_MODULES), y)
  C_CONFIG += -DCONFIG_MODULES=1
else
  C_CONFIG += -DCONFIG_MODULES=0
endif

ifeq ($(CONFIG_MODULE_FORCE_LOAD), y)
  C_CONFIG += -DCONFIG_MODULE_FORCE_LOAD=1
else
  C_CONFIG += -DCONFIG_MODULE_FORCE_LOAD=0
endif

ifeq ($(CONFIG_MODULE_FORCE_UNLOAD), y)
  C_CONFIG += -DCONFIG_MODULE_FORCE_UNLOAD=1
else
  C_CONFIG += -DCONFIG_MODULE_FORCE_UNLOAD=0
endif

ifeq ($(CONFIG_MODULE_SIG_FORCE), y)
  C_CONFIG += -DCONFIG_MODULE_SIG_FORCE=1
else
  C_CONFIG += -DCONFIG_MODULE_SIG_FORCE=0
endif

ifneq ($(CONFIG_MODULE_MAX_SIZE),)
  C_CONFIG += -DCONFIG_MODULE_MAX_SIZE=$(CONFIG_MODULE_MAX_SIZE)
endif
